# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TriangleTwo = QtWidgets.QLabel(self.centralwidget)
        self.TriangleTwo.setGeometry(QtCore.QRect(110, 420, 61, 61))
        self.TriangleTwo.setText("")
        self.TriangleTwo.setPixmap(QtGui.QPixmap(":/icons/icons/triangle.svg"))
        self.TriangleTwo.setObjectName("TriangleTwo")
        self.Turtle = QtWidgets.QLabel(self.centralwidget)
        self.Turtle.setGeometry(QtCore.QRect(380, 280, 51, 61))
        self.Turtle.setText("")
        self.Turtle.setPixmap(QtGui.QPixmap(":/icons/icons/turtleUp.svg"))
        self.Turtle.setObjectName("Turtle")
        self.TriangleOne = QtWidgets.QLabel(self.centralwidget)
        self.TriangleOne.setGeometry(QtCore.QRect(660, 120, 61, 61))
        self.TriangleOne.setText("")
        self.TriangleOne.setPixmap(QtGui.QPixmap(":/icons/icons/triangleRotated.svg"))
        self.TriangleOne.setObjectName("TriangleOne")
        self.Coin = QtWidgets.QLabel(self.centralwidget)
        self.Coin.setGeometry(QtCore.QRect(390, 180, 31, 31))
        self.Coin.setText("")
        self.Coin.setPixmap(QtGui.QPixmap(":/icons/icons/coin.svg"))
        self.Coin.setObjectName("Coin")
        self.Number = QtWidgets.QLabel(self.centralwidget)
        self.Number.setGeometry(QtCore.QRect(70, 20, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Number.setFont(font)
        self.Number.setObjectName("Number")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(730, 20, 18, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Number.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "0"))

import icons_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
